// Code generated by snek; DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"
)

var packageCmd = &cobra.Command{
	Use:     "package",
	Aliases: []string{"pkg"},
	Short:   "package daz3d content",
	Long:    "package daz3d content",
	Run:     packageCmdRun,
}

func init() {
	rootCmd.AddCommand(packageCmd)
	packageCmd.Flags().StringP("dir", "d", "", "directory to package")
}
