// Code generated by snek; DO NOT EDIT.
package cmd

import (
	"github.com/spf13/cobra"
)

var packageCmd = &cobra.Command{
	Use:     "package",
	Aliases: []string{"pkg"},
	Short:   "package daz3d content",
	Long:    "package daz3d content",
	Args:    cobra.ExactArgs(1),
	Run:     packageCmdRun,
}

func init() {
	rootCmd.PersistentFlags().StringP("prefix", "p", "CH", "prefix for package: default CH")
	rootCmd.AddCommand(packageCmd)
}
